# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Pratikshya2

'on': push
    
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Pratikshya Steps check
      run: mvn -B package --file pom.xml
