# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Pratikshya Maven Package

on:
  workflow_dispatch:
  push:
    branches: ["multipleTestWithJunitReport"]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Maven
      run: mvn test
      
    - name: git action adding test report
      run: |
          git config --global user.email pratikshya.samantaray@onbe.com         
          git config --global user.name "pratikshyaSamantaray94"
          git add target/surefire-reports/junitreports/TEST-GitHub.ActionsPOC.ActionsPOCTest.xml
          git add target/surefire-reports/junitreports/TEST-GitHub.ActionsPOC.ActionsPOCTest2.xml
          git commit -m "Adding junit report folder"
          git config --global pull.ff only 
          git push origin HEAD:master --force

     
   # - name: Upload Junit results in BrowserStack and print the logs in a file
     # run: |
       #     curl -u sulagnachakrabor_hF8bLJ:1bt4ji6nzS6ALopzMHZq -F 'data=@"TEST-GitHub.ActionsPOC.ActionsPOCTest.xml"' -F "projectName=TestNg Test Project" -F "buildName=Sample Build 2" https://upload-observability.browserstack.com/upload
 #   - name: Upload jUnit test results
   #   uses: actions/upload-artifact@v4
  #    with:
      #      name: jUnitReportTestNgxml
       #     path: "target/surefire-reports/junitreports/TEST-GitHub.ActionsPOC.ActionsPOCTest.xml"  
