# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: TestNg Artifact 

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Maven
      continue-on-error: true
      run: mvn test

    - name: git action adding test report
      run: |
               git config --global user.email "${{ secrets.GITHUBEMAIL }}"
               git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
               git add "target/surefire-reports/emailable-report.html"
               git commit -m "adding latest emailable reports"
               git config --global pull.ff only 
               git push origin HEAD:master --force 
               
    - name: Upload HTML test results
      uses: actions/upload-artifact@v4
      with:
           name: HTMLReport
           path: "target/surefire-reports/emailable-report.html" 
           
    - name: Get Artifact ID
      id: get_artifact_id
      run: |
             ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts"| jq -r '.artifacts[0].id')

             # Extract the artifact ID from the response
             #ARTIFACT_ID=$(echo "$response" | jq -r '.artifacts[0].id')
             echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
        
    - name: Get artifact link
      run: echo "ARTIFACT_LINK={https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${ARTIFACT_ID}}" >> $GITHUB_ENV
       
    - name: Output artifact link
      run: echo "$ARTIFACT_LINK"
             
    - name: Get Jira issue key
      id: get-issue-key
      run: | 
              echo "issue-key=$(echo ${{ github.event.pull_request.title }} | sed 's/^\\[\\(\\w\\+-\\d+\\)\\].*/\\1/')" >> $GITHUB_OUTPUT
    
    - name: Check issue key value
      run: echo ${{ steps.get-issue-key.outputs.issue-key }}
        
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
             JIRA_BASE_URL: https://onbe-sandbox-213.atlassian.net
             JIRA_USER_EMAIL: ${{ secrets.GITHUBEMAIL }}
             JIRA_API_TOKEN: ${{ secrets.JIRAAPITOKEN }}

          
    - name: Jira Add Comment
      uses: atlassian/gajira-comment@v3
      with:
           issue: ${{ steps.get-issue-key.outputs.issue-key }}
           comment: Check Report in the git artifact link ${{ env.ARTIFACT_LINK }}.
           
           
   
 

