# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: TestNg Artifact 

on: [push]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Maven
      run: mvn test

  deploy:
    runs-on: windows-latest

    needs: build

    steps:
      - name: git action adding test report
        run: |
               git config --global user.email pratikshya.samantaray@onbe.com         
               git config --global user.name "pratikshyaSamantaray94"
               git add "target/surefire-reports/emailable-report.html"
               git commit -m "adding latest emailable reports"
               git config --global pull.ff only 
               git push origin HEAD:master --force 
               
      - name: Upload HTML test results
        uses: actions/upload-artifact@v4
        with:
           name: HTMLReport
           path: "target/surefire-reports/emailable-report.html" 

    options:
           continue-on-error: true
 

