# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Pratikshya Maven Package

on: [push]
 # workflow_dispatch:
 # push:
   # branches: ["multipleTestWithJunitReport"]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Maven
      run: mvn test
      
    - name: Upload HTML test results
      uses: actions/upload-artifact@v4
      with:
           name: HTMLReport
           path: "test-output/emailable-report.html" 
