

name: TestNg Artifact github Report in JiraNew

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run with Maven
      continue-on-error: true
      run: |
            mvn dependency:resolve
            mvn clean install

    - name: git action adding test report
      run: |
               git config --global user.email "${{ secrets.GITHUBEMAIL }}"
               git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
               git add "target/surefire-reports/emailable-report.html"
               git commit -m "adding latest emailable reports"
               git config --global pull.ff only 
               git push origin HEAD:master --force 
    - name: Pull HTML report
      run: |  
           rm target/surefire-reports/emailable-report.html  
           mv target/surefire-reports/emailable-report.html   
           
    - name: Commit and push changes
      run:  |         
            git config --global user.name "${{ secrets.GITHUBEMAIL }}"         
            git config --global user.email "${{ secrets.GITHUBUSERNAME }}"         
            git add "emailable-report.html"         
            git commit -m "Pull HTML report from test-output folder"  
            git config --global pull.ff only
            git push origin HEAD:master --force    
            
    - name: Upload HTML test results
      uses: actions/upload-artifact@v4
      with:
           name: HTMLReport
           path: "emailable-report.html" 

  deploy:

    runs-on: ubuntu-latest
    needs: build
    steps:         
    - name: Get Artifact ID
      id: get_artifact_id
      run: |
                ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
                        "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts" \
                        | jq -r '.artifacts[0].id')
                echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV

        
    - name: Get artifact link
      run: echo "ARTIFACT_LINK={https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${ARTIFACT_ID}}" >> $GITHUB_ENV
       
    - name: Output artifact link
      run: echo "$ARTIFACT_LINK"
             
    - name: Get Jira issue key
      id: get-issue-key
      run: | 
            title="${{ github.event.pull_request.title }}"
               IFS='|' read -ra title_parts <<< "$title"
               echo "issue-key=$(echo ${title_parts[0]} | sed 's/^\\[\\(\\w\\+-\\d+\\)\\].*/\\1/')" >> $GITHUB_OUTPUT
    
    - name: Check issue key value
      run: echo ${{ steps.get-issue-key.outputs.issue-key }}
        
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
             JIRA_BASE_URL: https://onbe-sandbox-213.atlassian.net
             JIRA_USER_EMAIL: sulagna.chakraborty@onbe.com
             JIRA_API_TOKEN: ${{ secrets.JIRAAPITOKEN }}

          
    - name: Jira Add Comment
      uses: atlassian/gajira-comment@v3
      with:
           issue: ${{ steps.get-issue-key.outputs.issue-key }}
           comment: Check TestNg Html Report in the git artifact link ${{ env.ARTIFACT_LINK }}
           
           
   
 

